### ISSUE TITLE
For Becky - Soil types differ throughout rb209

### ISSUE THREAD

**Issue by amberfoam** [nebogeo/crapapppro#17]
In most places the categories are:
sandy/shallow
medium/shalllow
deep clay
deep silt
organic
peat

On the table on p105, the categories are:
light sand
shallow
medium
deep clay
deep silt
organic
peat

On this table the values for the first three categories differ. What should we do?

**Comment by beckyduchy** [comment]
ok 
the first categories are what generates the soil nitrogen supply and also the manure availability data.
The table on page 105 for winter wheat and the table on page 111 for spring barley differentiate using a different categories but it seems to be just splitting out sandy and shallow. Is there a way we could when they set up the field choose from the extended list as that is where they are going to be generating the recommendations?
For the calculator could we just have a range of N recommendtaions or would that not be an option?
thanks
becky

**Comment by nebogeo** [comment]
in efforts to prevent this getting too complex (!) currently I'm converting 
- sandyshallow -> lightsand 
- mediumshallow -> shallowsoils 
and medium is not used

**Comment by beckyduchy** [comment]
Could we have light sand and then medium? (sorry to be a pain) but a lot of farmers identify their soil type as medium, so would enhance usability.
