### ISSUE TITLE
For Becky - Grass requirements for P & K?

### ISSUE THREAD

**Issue by nebogeo** [nebogeo/crapapppro#18]
not sure if these are missing/needed...

**Comment by beckyduchy** [comment]
They are needed! Sorry if I didn't send them. I will endeavour to attach them now

**Comment by beckyduchy** [comment]
[rb209-fertiliser-manual-110412.pdf](https://github.com/nebogeo/crapapppro/files/621657/rb209-fertiliser-manual-110412.pdf)
 pages 210 - 211

**Comment by nebogeo** [comment]
for cut grass, I'm using first cut values - is that right?

**Comment by nebogeo** [comment]
and for K - spring cut, just choosing hopefully sensible defaults

**Comment by beckyduchy** [comment]
Yep sounds right to me, for grazed grass its the table on 210, for silage its the table on page 211 and use first cut options, and spring application for potash (using the soil analysis data).
