### ISSUE TITLE
organic soil 

### ISSUE THREAD

**Issue by beckyduchy** [nebogeo/crapapppro#30]
feedback from Steve - organic soil (and to a lesser extent peat) - farmers may get confused that we are talking about soil from organic farms rather than the classification of organic soil through RB209 (10-20% organic matter).
Is there any opportunity to have a pop up box (or something else) that explains the difference.

**Comment by nebogeo** [comment]
I've changed it from "Organic" to "Organic (10-20% organic matter)", is that ok?

**Comment by beckyduchy** [comment]
sounds fab thank you
