### ISSUE TITLE
organic calculations

### ISSUE THREAD

**Issue by beckyduchy** [nebogeo/crapapppro#33]
did a calculation using pig FYM in autumn with soil results 2 for phosphate and 2- for potash, its pulling crop available instead of total

**Comment by nebogeo** [comment]
isn't crop available what we want? that's what it says over the figures :)

**Comment by beckyduchy** [comment]
Yep - but there is the caveat that if the soil indices is 2 or more then you use the total (as you are just topping up soil supply as the soil can provide what the crop needs

**Comment by nebogeo** [comment]
ahah, is this for all manures?

**Comment by beckyduchy** [comment]
yep if soil indices are 2 or above for phosphate and potash you use total rather than crop available in nutrient plan,l hope that's ok

**Comment by nebogeo** [comment]
yep, no worries - just great that you can check all this as there is so much complexity!!

**Comment by beckyduchy** [comment]
im sorry its a real PITA I appreciate that!
